import java.awt.*;
import java.awt.event.*;
import java.applet.*;
import javax.swing.*;

public class Exercise24_6 extends javax.swing.JApplet {
  // Create an array of strings for figure names
  String[] figures = {"Square", "Rectangle", "Circle", "Oval"};

  // Create a list cell renderer
  Exercise24_6CellRenderer myListCellRenderer =
    new Exercise24_6CellRenderer();

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList jList1;
  private FigurePanel figurePanel;
  // End of variables declaration//GEN-END:variables

  /** Creates new form Exercise24_6 */
  public Exercise24_6() {
    initComponents();

    //
    jList1.setListData(figures);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    figurePanel = new FigurePanel();

    jList1.setCellRenderer(myListCellRenderer);
    jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        jList1ValueChanged(evt);
      }
    });

    jScrollPane1.setViewportView(jList1);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.WEST);

    getContentPane().add(figurePanel, java.awt.BorderLayout.CENTER);

  }//GEN-END:initComponents

  private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {
    String figure = (String)(jList1.getSelectedValue());

    if (figure.equals("Square"))
      figurePanel.setFigureType(1);
    else if (figure.equals("Rectangle"))
      figurePanel.setFigureType(2);
    else if (figure.equals("Circle"))
      figurePanel.setFigureType(3);
    else if (figure.equals("Oval"))
      figurePanel.setFigureType(4);

    figurePanel.repaint();
  }

  public static void main(String[] args) {
    Exercise24_6 applet = new Exercise24_6();
    JFrame frame = new JFrame();
    //EXIT_ON_CLOSE == 3
    frame.setDefaultCloseOperation(3);
    frame.setTitle("Exercise24_6");
    frame.getContentPane().add(applet, BorderLayout.CENTER);
    applet.init();
    applet.start();
    frame.setSize(400,320);
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    frame.setLocation((d.width - frame.getSize().width) / 2, (d.height - frame.getSize().height) / 2);
    frame.setVisible(true);
  }
}