;  CSC 218, Assignment #9
;  Provided Main Program.

; DO NOT EDIT THIS FILE!



.model	small

; ---------------------------------------------------------------

.data

; -----
; Constants.

LF	equ	10			; line feed
CR	equ	13			; carridge return
END_STR	equ	"$"			; end of string


; -----
;  Variables for main.

intro		db	CR, LF, "**************************************"
		db	CR, LF, "CSC218 - Race Time Calculation Program"
		db	CR, LF, CR, LF, END_STR


r_name		db	31 dup (20h)

r_start_day	db	?			; 0=Su, 1=Mo, etc.
r_start_time	db	?, ?, ?			; hours, mins, secs

r_len		db	?, ?, ?			; hours, mins, secs

r_end_day	db	?			; 0=Su, 1=Mo, etc.
r_end_time	db	?, ?, ?			; hours, mins, secs


; ---------------------------------------------------------------

.stack

.code

extrn	read_race_info:near
extrn	calc_end_time:near
extrn	disp_race_info:near


; ---------------

main	proc	far
	mov	ax, @data		; initialization
	mov	ds, ax

; -----
;  Display intro message.

	mov	ah, 09h
	lea	dx, intro
	int	21h

; -----
;  Get race information.
;  Includes race name, start day, start time (h/m/s), and race
;  length (h/m/s).
;  Note, procedure performs all error checking and conversion
;  of ASCII date to interger.

	lea	ax, r_name
	push	ax
	lea	ax, r_start_day
	push	ax
	lea	ax, r_start_time
	push	ax
	lea	ax, r_len
	push	ax
	call	read_race_info


; -----
;  Calculate race end day and time (h/m/s).
;  Uses race start day, race start time, and race length.

	lea	ax, r_start_day
	push	ax
	lea	ax, r_start_time
	push	ax
	lea	ax, r_len
	push	ax
	lea	ax, r_end_day
	push	ax
	lea	ax, r_end_time
	push	ax
	call	calc_end_time


;  Display race information.
;  Includes race name, race start day, race start time,
;  race end day, and race end time.
;  Note, converts 24 hours times to 12 hour AM/PM format.
;  Procedure converts integer times to ASCII for display.

	lea	ax, r_name
	push	ax
	lea	ax, r_start_day
	push	ax
	lea	ax, r_start_time
	push	ax
	lea	ax, r_end_day
	push	ax
	lea	ax, r_end_time
	push	ax
	call	disp_race_info


; -----
;  Done, terminate program.

last:
	mov	ah, 4ch
	int	21h

main	endp

end	main
